(() => {
'use strict';
const DATA='./data/posts.json', AUTHORS='./data/authors.json', TOPICS='./data/topics.json';
const KEY={posts:'small-signals.local-posts.v10',likes:'small-signals.likes.v10',reposts:'small-signals.reposts.v10',bookmarks:'small-signals.bookmarks.v10',following:'small-signals.following.v10'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const el={content:$('#viewContent'),title:$('#viewTitle'),subtitle:$('#viewSubtitle'),tabs:$('#feedTabs'),composer:$('#inlineComposer'),inlineText:$('#inlineText'),inlineSubmit:$('#inlineSubmit'),back:$('#backButton'),sentinel:$('#sentinel'),dialog:$('#composerDialog'),dialogText:$('#dialogText'),dialogSubmit:$('#dialogSubmit'),dialogTitle:$('#dialogTitle'),dialogCount:$('#dialogCount'),replyPreview:$('#replyPreview'),toast:$('#toast'),topicList:$('#topicList'),suggested:$('#suggestedAuthors'),sideSearch:$('#sideSearch'),badge:$('#notificationBadge')};
const read=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??d}catch{return d}}, save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const set=(k,d=[])=>new Set(read(k,d)), likes=set(KEY.likes), reposts=set(KEY.reposts), bookmarks=set(KEY.bookmarks), following=set(KEY.following,['nagi_00','half_asleep','yuge']);
let authors=[],authorMap=new Map(),remote=[],local=read(KEY.posts,[]),topics=[],posts=[],postMap=new Map(),feed='for-you',items=[],cursor=0,observer,replyTo=null;
const fallbackAuthors=[{handle:'you',name:'あなた',avatar:'◌',tone:0,bio:'この端末からの投稿。',location:'ここ'},{handle:'nagi_00',name:'凪',avatar:'凪',tone:5,bio:'何も起きない日の記録。',location:'風のない場所'},{handle:'half_asleep',name:'ねむい',avatar:'眠',tone:7,bio:'寝るほどではない。',location:'布団の外'},{handle:'yuge',name:'湯気',avatar:'湯',tone:12,bio:'食べ物と飲み物。',location:'台所'}];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function norm(p,i=0){const m=p?.metrics||{},id=String(p?.id||`p-${i}-${hash(p?.text||i)}`);return{id,text:String(p?.text||'').trim(),kind:String(p?.kind||'ordinary'),author:String(p?.author||p?.author_id||'nagi_00'),created_at:p?.created_at||new Date(Date.now()-i*60000).toISOString(),reply_to:p?.reply_to||p?.parent_id||null,quote_to:p?.quote_to||p?.quote_id||null,conversation_id:p?.conversation_id||null,topic:p?.topic||null,replies:Number(p?.replies??m.replies??0),reposts:Number(p?.reposts??m.reposts??0),likes:Number(p?.likes??m.likes??0),views:Number(p?.views??m.views??(30+hash(id)%2200)),local:Boolean(p?.local)}}
function rebuild(){const u=new Map();[...local.map(norm),...remote.map(norm)].forEach(p=>p.text&&u.set(p.id,p));posts=[...u.values()];postMap=u}
const getPost=id=>postMap.get(String(id)), getAuthor=h=>authorMap.get(h)||{handle:h||'unknown',name:h||'不明',avatar:'·',tone:0,bio:'',location:''};
const direct=id=>posts.filter(p=>p.reply_to===id).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));
const time=v=>{const d=new Date(v),n=Date.now()-d;if(!Number.isFinite(d.getTime()))return'';if(n<60000)return'いま';if(n<3600000)return`${Math.max(1,n/60000|0)}分`;if(n<86400000)return`${n/3600000|0}時間`;return`${d.getMonth()+1}月${d.getDate()}日`};
const compact=n=>n<1000?(n?String(n):''):n<10000?`${(n/1000).toFixed(1)}千`:`${(n/10000).toFixed(1)}万`;
const route=()=>((location.hash.replace(/^#\/?/,'')||'home').split('/').map(decodeURIComponent));
function go(r){const h=`#/${r}`;location.hash===h?render():location.hash=h}
function header(title,sub='',tabs=false,back=false){el.title.textContent=title;el.subtitle.textContent=sub;el.subtitle.hidden=!sub;el.tabs.hidden=!tabs;el.composer.hidden=!tabs;el.sentinel.hidden=!tabs;el.back.hidden=!back}
function toast(s){el.toast.textContent=s;el.toast.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.hidden=true,1700)}
async function json(url,fallback){try{const r=await fetch(`${url}?v=10-${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}catch{return fallback}}
async function load(){const [a,p,t]=await Promise.all([json(AUTHORS,{authors:fallbackAuthors}),json(DATA,{posts:[]}),json(TOPICS,{topics:[]})]);authors=Array.isArray(a.authors)?a.authors:fallbackAuthors;if(!authors.some(x=>x.handle==='you'))authors.unshift(fallbackAuthors[0]);authorMap=new Map(authors.map(x=>[x.handle,x]));remote=Array.isArray(p.posts)?p.posts:[];topics=Array.isArray(t.topics)?t.topics:[];rebuild()}
function action(icon,count,cls,id,active=false){return`<button class="post-action ${cls}${active?' is-active':''}" data-action="${cls}" data-id="${esc(id)}"><span class="icon">${icon}</span><small>${compact(count)}</small></button>`}
function card(p,opt={}){const a=getAuthor(p.author),parent=p.reply_to&&getPost(p.reply_to),quote=p.quote_to&&getPost(p.quote_to),count=direct(p.id).length||p.replies;const article=document.createElement('article');article.className=`post${opt.detail?' is-detail':''}${opt.ancestor?' thread-ancestor':''}`;article.dataset.id=p.id;article.tabIndex=0;article.innerHTML=`<button class="post-avatar-button" data-profile="${esc(a.handle)}"><span class="avatar large tone-${Number(a.tone)||0}">${esc(a.avatar||a.name?.[0]||'·')}</span></button><div class="post-main"><div class="post-meta"><button class="author-name" data-profile="${esc(a.handle)}">${esc(a.name)}${a.verified?' ◉':''}</button><span class="author-handle">@${esc(a.handle)}</span><span>·</span><time>${time(p.created_at)}</time><button class="more-button" data-action="more">•••</button></div>${parent?`<p class="replying-to">返信先: <span>@${esc(getAuthor(parent.author).handle)}</span></p>`:''}${p.topic?`<span class="topic-label">${esc(p.topic.source||'いまの話題')}</span>`:''}<p class="post-text">${esc(p.text)}</p>${quote?`<div class="quote-card" data-post="${esc(quote.id)}"><strong>${esc(getAuthor(quote.author).name)} @${esc(quote.author)}</strong>\n${esc(quote.text)}</div>`:''}<div class="post-actions">${action('◯',count,'reply-action',p.id)}${action('⇄',p.reposts+(reposts.has(p.id)?1:0),'repost-action',p.id,reposts.has(p.id))}${action('♡',p.likes+(likes.has(p.id)?1:0),'like-action',p.id,likes.has(p.id))}${action('▥',p.views,'view-action',p.id)}${action('◇',0,'bookmark-action',p.id,bookmarks.has(p.id))}${action('↥',0,'share-action',p.id)}</div></div>`;return article}
function feedSort(src){return [...src].sort((a,b)=>{if(a.local!==b.local)return a.local?-1:1;return new Date(b.created_at)-new Date(a.created_at)})}
function renderBatch(){const f=document.createDocumentFragment();items.slice(cursor,cursor+28).forEach(p=>f.append(card(p)));cursor+=28;el.content.append(f)}
function observe(){observer?.disconnect();observer=new IntersectionObserver(e=>e.some(x=>x.isIntersecting)&&renderBatch(),{rootMargin:'900px'});observer.observe(el.sentinel)}
function home(){header('ホーム','',true,false);const src=feed==='following'?posts.filter(p=>following.has(p.author)||p.author==='you'):posts;items=feedSort(src);cursor=0;el.content.replaceChildren();renderBatch();observe()}
function ancestors(p){const a=[],seen=new Set();let x=p.reply_to&&getPost(p.reply_to);while(x&&!seen.has(x.id)){seen.add(x.id);a.unshift(x);x=x.reply_to&&getPost(x.reply_to)}return a}
function branch(p,depth=0){const wrap=document.createElement('div');wrap.className=`branch depth-${Math.min(depth,2)}`;wrap.append(card(p));const kids=direct(p.id);kids.slice(0,depth?2:3).forEach(k=>wrap.append(branch(k,depth+1)));if(kids.length>(depth?2:3)){const b=document.createElement('button');b.className='expand-replies';b.textContent=`返信をさらに表示（${kids.length-(depth?2:3)}件）`;b.onclick=e=>{e.stopPropagation();b.remove();kids.slice(depth?2:3).forEach(k=>wrap.append(branch(k,depth+1)))};wrap.append(b)}return wrap}
function thread(id){const p=getPost(id);header('ポスト','',false,true);el.content.replaceChildren();if(!p)return empty('ポストが見つかりません','ホームへ戻ってください。');ancestors(p).forEach(x=>el.content.append(card(x,{ancestor:true})));el.content.append(card(p,{detail:true}));const c=document.createElement('div');c.className='thread-compose';c.innerHTML=`<span class="avatar tone-0">◌</span><button data-reply="${esc(p.id)}">返信をポスト</button><button class="primary-small" data-reply="${esc(p.id)}">返信</button>`;el.content.append(c);const rs=direct(p.id);if(!rs.length)return empty('まだ返信はありません','最初の返信を送れます。');const label=document.createElement('div');label.className='section-label';label.textContent=`返信 ${rs.length}件`;el.content.append(label);rs.forEach(r=>el.content.append(branch(r)))}
function profile(handle){const a=getAuthor(handle),mine=posts.filter(p=>p.author===handle).sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));header(a.name,`${mine.length}件のポスト`,false,true);el.content.replaceChildren();const s=document.createElement('section');s.innerHTML=`<div class="profile-cover"></div><div class="profile-body"><div class="profile-top"><span class="avatar profile-avatar tone-${Number(a.tone)||0}">${esc(a.avatar||'·')}</span>${handle==='you'?'':`<button class="follow-button${following.has(handle)?' is-following':''}" data-follow="${esc(handle)}">${following.has(handle)?'フォロー中':'フォロー'}</button>`}</div><h2 class="profile-name">${esc(a.name)}${a.verified?' ◉':''}</h2><p class="profile-handle">@${esc(a.handle)}</p><p>${esc(a.bio||'')}</p><p class="profile-location">${esc(a.location||'')}</p><div class="profile-stats"><span><strong>${following.has(handle)?1:0}</strong> フォロー中</span><span><strong>${Math.max(12,mine.length*4)}</strong> フォロワー</span></div></div>`;el.content.append(s);mine.forEach(p=>el.content.append(card(p)));if(!mine.length)empty('まだポストがありません','ここに表示されます。')}
function explore(){header('話題を検索','',false,false);el.content.replaceChildren();const box=document.createElement('div');box.className='explore-search';box.innerHTML='<input type="search" placeholder="ポストやアカウントを検索">';el.content.append(box);const out=document.createElement('div');el.content.append(out);const draw=()=>{out.replaceChildren();const q=$('input',box).value.trim().toLowerCase();if(!q&&topics.length){topics.slice(0,12).forEach(t=>{const d=document.createElement('div');d.className='explore-topic';d.innerHTML=`<small>${esc(t.source||'ニュース')} · いまの話題</small><strong>${esc(t.title)}</strong><span>関連するポストを検索</span>`;d.onclick=()=>{$('input',box).value=t.title.slice(0,28);draw()};out.append(d)});return}const found=(q?posts.filter(p=>p.text.toLowerCase().includes(q)||getAuthor(p.author).name.toLowerCase().includes(q)||p.author.toLowerCase().includes(q)):feedSort(posts).slice(0,30)).slice(0,100);found.forEach(p=>out.append(card(p)));if(!found.length)out.innerHTML='<div class="empty"><p>一致するポストはありません。</p></div>'};$('input',box).oninput=draw;draw();$('input',box).focus()}
function notifications(){header('通知','',false,false);el.content.replaceChildren();const own=new Set(posts.filter(p=>p.author==='you').map(p=>p.id)),rs=posts.filter(p=>p.reply_to&&own.has(p.reply_to)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(!rs.length)return empty('新しい通知はありません','返信が届くとここに表示されます。');rs.forEach(p=>{const a=getAuthor(p.author),d=document.createElement('div');d.className='notification';d.innerHTML=`<span>◯</span><div><strong>${esc(a.name)}</strong> があなたに返信しました<p>${esc(p.text)}</p></div>`;d.onclick=()=>go(`post/${p.id}`);el.content.append(d)});el.badge.hidden=true}
function saved(){header('保存済み','',false,false);el.content.replaceChildren();const x=posts.filter(p=>bookmarks.has(p.id));x.forEach(p=>el.content.append(card(p)));if(!x.length)empty('保存したポストはありません','◇を押すとここに残ります。')}
function empty(h,p){const d=document.createElement('div');d.className='empty';d.innerHTML=`<h2>${esc(h)}</h2><p>${esc(p)}</p>`;el.content.append(d)}
function render(){const [r,id]=route();$$('[data-route]').forEach(x=>x.classList.toggle('is-active',x.dataset.route===r||(r==='profile'&&x.dataset.route===`profile/${id}`)));if(r==='post')thread(id);else if(r==='profile')profile(id);else if(r==='explore')explore();else if(r==='notifications')notifications();else if(r==='bookmarks')saved();else home();window.scrollTo({top:0,behavior:'instant'})}
function openComposer(id=null){replyTo=id;const p=id&&getPost(id);el.dialogTitle.textContent=p?'返信をポスト':'ポストする';el.dialogText.value='';el.dialogCount.textContent='0';el.dialogSubmit.disabled=true;if(p){const a=getAuthor(p.author);el.replyPreview.hidden=false;el.replyPreview.innerHTML=`<strong>@${esc(a.handle)} への返信</strong><br>${esc(p.text.slice(0,130))}`}else el.replyPreview.hidden=true;el.dialog.showModal();setTimeout(()=>el.dialogText.focus(),0)}
function submit(text,id=null){const clean=String(text).trim().slice(0,180);if(!clean)return;const p=norm({id:`local-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,text:clean,author:'you',created_at:new Date().toISOString(),reply_to:id,local:true,views:1});local.unshift(p);local=local.slice(0,1000);save(KEY.posts,local);rebuild();el.inlineText.value='';el.inlineSubmit.disabled=true;el.dialog.close();toast(id?'返信をポストしました':'ポストしました');go(id?`post/${id}`:'home')}
function toggle(s,k,id){s.has(id)?s.delete(id):s.add(id);save(k,[...s])}
function topicsSide(){el.topicList.replaceChildren();const list=topics.length?topics.slice(0,5):[{title:'何でもないこと',source:'微弱信号'},{title:'短い会話',source:'微弱信号'},{title:'まだ起きている',source:'微弱信号'}];list.forEach(t=>{const b=document.createElement('button');b.className='topic-item';b.innerHTML=`<small>${esc(t.source||'ニュース')} · いまの話題</small><strong>${esc(t.title)}</strong><span>関連するポスト</span>`;b.onclick=()=>{go('explore');setTimeout(()=>{const i=$('.explore-search input');if(i){i.value=t.title.slice(0,30);i.dispatchEvent(new Event('input'))}},0)};el.topicList.append(b)})}
function suggested(){el.suggested.replaceChildren();authors.filter(a=>a.handle!=='you').slice(0,4).forEach(a=>{const d=document.createElement('div');d.className='suggested';d.innerHTML=`<span class="avatar tone-${Number(a.tone)||0}">${esc(a.avatar||'·')}</span><button class="suggested-copy" data-profile="${esc(a.handle)}"><strong>${esc(a.name)}</strong><small>@${esc(a.handle)}</small></button><button class="follow-button${following.has(a.handle)?' is-following':''}" data-follow="${esc(a.handle)}">${following.has(a.handle)?'フォロー中':'フォロー'}</button>`;el.suggested.append(d)})}
function events(){window.onhashchange=render;document.addEventListener('click',async e=>{const r=e.target.closest('[data-route]');if(r){go(r.dataset.route);return}const pr=e.target.closest('[data-profile]');if(pr){e.stopPropagation();go(`profile/${pr.dataset.profile}`);return}const fl=e.target.closest('[data-follow]');if(fl){e.stopPropagation();toggle(following,KEY.following,fl.dataset.follow);render();suggested();return}const rp=e.target.closest('[data-reply]');if(rp){e.stopPropagation();openComposer(rp.dataset.reply);return}const q=e.target.closest('[data-post]');if(q){e.stopPropagation();go(`post/${q.dataset.post}`);return}const b=e.target.closest('[data-action]');if(b){e.stopPropagation();const id=b.dataset.id,p=getPost(id),a=b.dataset.action;if(a==='reply-action')return openComposer(id);if(a==='like-action'){toggle(likes,KEY.likes,id);render()}else if(a==='repost-action'){toggle(reposts,KEY.reposts,id);render()}else if(a==='bookmark-action'){toggle(bookmarks,KEY.bookmarks,id);b.classList.toggle('is-active');toast(bookmarks.has(id)?'保存しました':'保存を解除しました')}else if(a==='share-action'){const url=`${location.href.split('#')[0]}#/post/${encodeURIComponent(id)}`;try{navigator.share?await navigator.share({text:p.text,url}):await navigator.clipboard.writeText(`${p.text}\n${url}`);toast('共有しました')}catch{}}else if(a==='more')toast('追加の操作はありません');return}const post=e.target.closest('.post');if(post)go(`post/${post.dataset.id}`)});$$('.feed-tab').forEach(b=>b.onclick=()=>{feed=b.dataset.feed;$$('.feed-tab').forEach(x=>x.classList.toggle('is-active',x===b));home()});el.inlineText.oninput=()=>el.inlineSubmit.disabled=!el.inlineText.value.trim();el.inlineSubmit.onclick=()=>submit(el.inlineText.value);$('#openComposer').onclick=()=>openComposer();$('#mobileComposer').onclick=()=>openComposer();$('#closeComposer').onclick=()=>el.dialog.close();el.dialogText.oninput=()=>{const n=[...el.dialogText.value].length;el.dialogCount.textContent=n;el.dialogSubmit.disabled=!el.dialogText.value.trim()||n>180};el.dialogSubmit.onclick=()=>submit(el.dialogText.value,replyTo);el.back.onclick=()=>history.length>1?history.back():go('home');el.sideSearch.onkeydown=e=>{if(e.key==='Enter'){go('explore');setTimeout(()=>{const i=$('.explore-search input');if(i){i.value=el.sideSearch.value;i.dispatchEvent(new Event('input'))}},0)}}}
async function clearOld(){try{for(const r of await navigator.serviceWorker?.getRegistrations?.()||[])await r.unregister();for(const n of await caches?.keys?.()||[])if(n.startsWith('small-signals'))await caches.delete(n)}catch{}}
async function init(){await clearOld();events();await load();topicsSide();suggested();render();const own=new Set(posts.filter(p=>p.author==='you').map(p=>p.id));el.badge.hidden=!posts.some(p=>p.reply_to&&own.has(p.reply_to))}
init().catch(e=>{console.error(e);el.content.innerHTML='<div class="empty"><h2>読み込みに失敗しました</h2><p>ページを再読み込みしてください。</p></div>'});
})();
